name: Deploy Next App
on: 
  push:
    branches: [main]
jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      SSH_KEY: ${{secrets.SECRET_SSH}}
      HOST: ${{secrets.HOST}}
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"
      - run: npm i 
      - run: npm run build
      - run: mkdir ~/.ssh
      - run: echo "$SSH_KEY" >> ~/.ssh/github-action
      - run: chmod 400 ~/.ssh/github-action
      - run: echo -e "Host vps\n\tUser root\n\tHostname $HOST\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config
      - run: rsync -re ssh ./build/ vps:/root/projects/nexjs-portfolio/build
      - run: ssh vps "pm2 restart portfolio-victor"
